DB_URI: "mongodb+srv://VladDotH:7bewRgq5hFaQN4NqyB8ZrZrS@vladdoth-cluster.c63tz.azure.mongodb.net/minecraft_server?retryWrites=true&w=majority"
DB_NAME: minecraft_server
DB_COL_NAME: users
DB_PLAYER_ID: _id

META_NOT_NATURAL: not_natural

JOB_MENU_NAME: Меню работы
SKILLS_MENU_NAME: Просмотр навыков
TIME_TO_CHANGE_JOB: 21_600_000

MAX_LVL: 100

BASE_MINE: 10
BASE_HARVEST: 10
BASE_LUBMER: 10
BASE_ATTACK: 40
BASE_SHEAR: 10
BASE_ANIMAL_DROP: 10
BASE_FISH: 10
MAX_DISP: 0.6

MINE_PER_LVL: 0.5
HARVEST_PER_LVL: 0.5
LUMBER_PER_LVL: 0.5
ATTACK_PER_LVL: 0.5
SHEAR_PER_LVL: 0.5
ANIMAL_DROP_PER_LVL: 0.5
FISH_PER_LVL: 0.5
MIN_DISP: 0.01

MINER_BONUS: 40.0
FARMER_BONUS: 40.0
LUMBER_BONUS: 40.0

HUNTER_BONUS_SHOOT: 1.3 # dispersion division
HUNTER_BONUS_DROP: 20
HUNTER_BONUS_ATTACK: 10

BREEDER_BONUS: 40.0 # bonus to drop from animals & shearing
FISHER_BONUS: 40.0

MINE_MISS: 0.01
LUMBER_MISS: 0.01
HARVEST_MISS: 0.01
ATTACK_MISS: 0.01
SHEAR_MISS: 0.01
ANIMAL_DROP_MISS: 0.01
FISH_MISS: 0.01


ATTACK_EXP: 0.10
SHEAR_EXP: 0.10
ANIMAL_DROP_EXP: 0.10
FISH_EXP: 0.50
SHOOT_MISS_EXP: 0.01
SHOOT_HIT_EXP: 0.10

# MINER
COAL_ORE: 0.10
REDSTONE_ORE: 0.10
IRON_ORE: 0.20
LAPIS_ORE: 0.20
GOLD_ORE: 0.40
DIAMOND_ORE: 0.60
EMERALD_ORE: 0.90

# WOODCUTTER
LOG: 0.20
LOG2: 0.25

# FARMER
CROPS: 0.10 #ПШЕНИЦА
SUGAR_CANE_BLOCK: 0.10 #ТРОСТНИК
POTATO: 0.10 #КАРТОФЕЛЬ
CARROT: 0.10 #МОРКОВЬ
PUMPKIN: 0.20 #ТЫКВА
MELON_BLOCK: 0.20 #АРБУЗ

# HUNTER & BREEDER
CREEPER: 0.20
ZOMBIE: 0.20
SKELETON: 0.20
WITCH: 0.40
PLAYER: 1
SPIDER: 0.20
CAVE_SPIDER: 0.30
ENDERMAN: 0.80

COW: 0.40
CHICKEN: 0.20
PIG: 0.30
SHEEP: 0.30
HORSE: 0.40