data_base_uri: mongodb+srv://VladDotH:7bewRgq5hFaQN4NqyB8ZrZrS@vladdoth-cluster.c63tz.azure.mongodb.net/minecraft_server?retryWrites=true&w=majority
data_base_name: minecraft_server
data_base_collection_name: users
data_base_id: _id

META_NOT_NATURAL: not_natural

MAX_LVL: 100

BASE_CHANCE_MINE: 10
BASE_CHANCE_HARVEST: 10
BASE_CHANCE_LUBMER: 10
BASE_CHANCE_ATTACK: 10

CHANCE_MINE_PER_LVL: 0.5
CHANCE_HARVEST_PER_LVL: 0.5
CHANCE_LUMBER_PER_LVL: 0.5
CHANCE_ATTACK_PER_LVL: 0.5

MINER_BONUS: 40.0
FARMER_BONUS: 40.0
LUMBER_BONUS: 40.0
HUNTER_BONUS: 40.0

MENU_NAME: Меню выбора работы
TIME_TO_CHANGE_JOB: 21_600_000

# MINER JOB
# EXPERIENCE FOR ORE MINING
COAL_ORE: 0.10
REDSTONE_ORE: 0.10
IRON_ORE: 0.20
LAPIS_ORE: 0.20
GOLD_ORE: 0.40
DIAMOND_ORE: 0.60
EMERALD_ORE: 0.90

# WOODCUTTER JOB
# EXPERIENCE FOR CUTTING WOOD
LOG: 0.20

# FARMER JOB
# EXPERIENCE FOR HARVESTING
CROPS: 0.10 #ПШЕНИЦА
SUGAR_CANE_BLOCK: 0.10 #ТРОСТНИК
POTATO: 0.10 #КАРТОФЕЛЬ
CARROT: 0.10 #МОРКОВЬ
PUMPKIN: 0.20 #ТЫКВА
MELON_BLOCK: 0.20 #АРБУЗ

# HUNTER JOB
# EXPERIENCE FOR ENEMIES
EXP_PER_HIT: 0.05
CREEPER: 0.20
ZOMBIE: 0.20
SKELETON: 0.20
WITCH: 0.40
PLAYER: 1
SPIDER: 0.20
CAVE_SPIDER: 0.30
ENDERMAN: 0.80
# EXPERIENCE FOR ANIMALS
COW: 0.40
CHICKEN: 0.20
PIG: 0.30
SHEEP: 0.30
HORSE: 0.40