name: KingsRP
version: ${project.version}
main: com.vladdoth.kings_rp_plugin.Plugin

commands:
  job:
    description: "Управление работами"
    aliases: [employ]

  skills:
    description: "Посмотреть навыки"
    aliases: [exp]
